language: python
python:
  - "3.7"
# command to install dependencies
install: 
  - pip install coveralls
# command to run tests
script:
  - python setup.py install 
  - nosetests --with-coverage
after_success: 
  - coveralls