dist: xenial
language: python
python:
  - "3.7"
# command to install dependencies
install: 
  - pip install coveralls flake8 sphinx
# command to run tests
script:
  - python setup.py install 
  - nosetests --with-coverage --with-doctest
  - flake8
after_success: 
  - coveralls