site_name: Picea documentation
repo_url: https://github.com/holmrenser/picea
plugins: 
    - search
    - mkapi
    - mkdocs-jupyter:
        execute: True
        kernel_name: python3
markdown_extensions:
    - admonition
    - codehilite
    - toc
theme:
    name: material
nav:
    - index.md
    - Examples:
        - examples/tree.ipynb
    - API:
        - API/sequence.md
        - API/tree.md