name: docs

on:
  push:
    branch: [master]

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Checkout master
        uses: actions/checkout@v1

      - name: Install picea
        run: |
          pip3 install setuptools
          pip3 install -r requirements.txt
          pip3 install -e .

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # REQUIREMENTS: docs/requirements.txt